apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep 
  
spec:
  replicas: 1
  selector:
    matchLabels:
      web: mysql
  
  template:
    metadata:
       labels:
         web: mysql

    spec:
      containers:
       - name: mysql-container
         image: amirmamdouh123/saay-mysql
         ports:
         - containerPort: 3306
         - containerPort: 22

